### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by shymega** [firerain42/mpris-rs#1]
Hi.

Was hoping to use this project for my project - rscribble - which is a modular scrobbler.

However, this project seems dead.

Is it still alive?

Thanks!

**Comment by firerain42** [comment]
Well, I would like to work on the project, but currently I have other priorities. So you should probably not expect much progress in the next time.

**Comment by Mange** [comment]
I have a library that might interest you. https://crates.io/crates/mpris

**Comment by shymega** [comment]
@firerain42 I understand, no worries.
@Mange Taken a look at your library, it seems pretty good. I'll be trying to integrate that library into my scrobbler for now, thanks! 👍
